package com.juanite.model.domain;

public enum Genres {

    ACTION, ADVENTURE, FPS, RTS, RPG, PLATFORMS, PUZZLE, RACING, SIMULATOR, ROGUELIKE, SOULSLIKE, SPORTS, INDIE,
    MULTIPLAYER, FIGHTING, SHOOTER, OPEN_WORLD;

}