package com.juanite.model.domain;

public enum Tags {

    ACTION, ADVENTURE, FPS, RTS, RPG, PLATFORMS, PUZZLE, RACING, SIMULATOR, ROGUELIKE, SOULSLIKE, SPORTS, INDIE,
    MULTIPLAYER, FIGHTING, SHOOTER, OPEN_WORLD, MMORPG, BATTLE_ROYALE, SURVIVAL, HORROR, NONE;

}